name: Build app

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7
      - run: cd app && ./gradlew build
      - run: cd app && ./gradlew checkstyleMain
      - run: cd app && ./gradlew test